326 checked out books by call number
TAMULib/fw-registry pull request #329
Opened 2024-02-04 19:31 UTC by rmathew1011

Resolves #326

2024-02-05 13:48 UTC, qtamu approved these changes

2024-02-06 16:38 UTC, kaladay requested changes

2024-02-06 16:38 UTC, kaladay commented on books-call-number/nodes/buildQuery.json
> +  "description": "",
Shorten name and add a description.

2024-02-06 16:38 UTC, kaladay commented on books-call-number/nodes/connectToLdp.json
> +  "description": "",
Add a description.

2024-02-06 16:38 UTC, kaladay commented on books-call-number/nodes/deleteCSVReport.json
> +  "description": "",
Shorten name and add a description.

2024-02-06 16:38 UTC, kaladay commented on books-call-number/nodes/deleteReport.json
> +  "description": "",
Shorten name and add a description.

2024-02-06 16:38 UTC, kaladay commented on books-call-number/nodes/email.json
> +  "description": "",
Shorten name and add a description.

2024-02-06 16:38 UTC, kaladay commented on books-call-number/nodes/zipReport.json
> +  "description": "",
Add description.

2024-02-06 16:38 UTC, kaladay commented on books-call-number/workflow.json
> +  "description": "",
Shorten name and add a description.

2024-02-06 16:43 UTC, kaladay requested changes

2024-02-06 16:43 UTC, kaladay commented on books-call-number/nodes/email.json
> +  "mailFrom": "{{bcn-mail-from}}",
These are different syntax that have different effects:
- `{{{bcn-mail-to}}}`
- `{{bcn-mail-to}}`
- `${bcn-mail-to}`

I think the three braces is from the fw configuration settings.
Either the two braces or dollar brace is what is needed here.
As I do not remember which, can you let me know that this is indeed correct?

2024-02-06 16:43 UTC, kaladay commented on books-call-number/nodes/email.json
> +
```suggestion

```
Delete trailing space.

2024-02-06 17:12 UTC, rmathew1011 commented on books-call-number/nodes/buildQuery.json
> +  "description": "",
Shortened name and added description

2024-02-06 17:14 UTC, rmathew1011 commented on books-call-number/nodes/connectToLdp.json
> +  "description": "",
Description added

2024-02-06 17:16 UTC, rmathew1011 commented on books-call-number/nodes/deleteCSVReport.json
> +  "description": "",
Shortened name and added a description.

2024-02-06 17:20 UTC, rmathew1011 commented on books-call-number/nodes/deleteReport.json
> +  "description": "",
Shortened name and added a description.

2024-02-06 17:23 UTC, rmathew1011 commented on books-call-number/nodes/email.json
> +  "description": "",
Shortened name and added a description.

2024-02-06 17:39 UTC, rmathew1011 commented on books-call-number/workflow.json
> +  "description": "",
Shortened name and added a description.

2024-02-06 17:39 UTC, rmathew1011 commented on books-call-number/nodes/zipReport.json
> +  "description": "",
Shortened name and added a description.

2024-02-06 18:47 UTC, kaladay requested changes

2024-02-06 18:47 UTC, kaladay commented on books-call-number/nodes/email.json
> +  "name": "Email checked-out items list",
I think we can still shorten this further.
```suggestion
  "name": "E-mail Items",
```

2024-02-06 18:47 UTC, kaladay commented on books-call-number/nodes/email.json
> +
Now there are two lines at the end.
There only needs to be a single EOL at the end of the file.

2024-02-06 18:47 UTC, kaladay commented on books-call-number/triggers/startTrigger.json
> +  "name": "FOLIO Create Book Report Workflow Trigger",
```suggestion
  "name": "Books Call Number Start Trigger",
```
Make the start trigger naming structure consistent with the rest of the workflows.

see: https://github.com/search?q=repo%3ATAMULib%2Ffw-registry+trigger&type=code

It seems that [Create Notes](https://github.com/TAMULib/fw-registry/blob/608d701f27ce511e24bd20e6883cdd21a35fe179/create-notes/triggers/startTrigger.json#L3) is the exception to the pattern and may need to be updated (but not updated here).

Alternatively, if setting this to have `FOLIO` in the name and `Workflow` instead of `Start` shows up differently

2024-02-06 18:47 UTC, kaladay commented on books-call-number/workflow.json
> +  "name": "Generate list of checked out books Workflow",
```suggestion
  "name": "Generate Checked-out List",
```

2024-02-06 18:47 UTC, kaladay commented on books-call-number/nodes/zipReport.json
> +  "name": "Compress book report",
```suggestion
  "name": "Compress Book Report",
```
Not required, but I suggest being grammatically correct.
As these are labels, aka Titles, the first letter of each word should be capitalized.

2024-02-06 18:47 UTC, kaladay commented on books-call-number/nodes/query.json
> +  "name": "Query list of books by call number.",
```suggestion
  "name": "Query by Call Number",
```
These are labels/titles and so should not have periods at the end of the sentence.

2024-02-06 18:47 UTC, kaladay commented on books-call-number/nodes/js/buildQuery.js
> +  ')';
```suggestion
')';
```

2024-02-06 18:47 UTC, kaladay commented on README.md
> +fw config set bcn-mail-from ***
This might not work here for reasons commented below.
The `{{bcn-mail-to}}` might not work where `{{{bcn-mail-to}}}` might work.
Can you please explicitly confirm/deny this?

I know that the `ldp-url` works and it uses three braces: `{{{ldp-url}}}` in rules below.

I cannot imagine why `mailTo` and `mailFrom` would be different from `url`.
If they are, then we need to document this somewhere, such as our wiki.

2024-02-06 18:47 UTC, kaladay commented on README.md
> +
This needs to be a table, such as the ones done above.
example:
```
These variables are required when triggering the workflow:
| Variable Name  | Allowed Values | Short Description |
| -------------- | -------------- | ----------------- |
```

see: https://github.com/TAMULib/fw-registry/blob/6c0053d1ca3333cc5e5bfba55a48fafa68d89289/README.md?plain=1#L420

2024-02-06 18:47 UTC, kaladay commented on README.md
> +User can inititate form submission from catalog_reports Book-Call-Number Report.
Please add the appropriate curl command as seen in other workflows in this readme.

```
Trigger the workflow using an **HTTP** request such as with **Curl**:
...
```

2024-02-06 18:47 UTC, kaladay commented on README.md
> +
Please add documentation like the following:
```suggestion

At the end of this process, an e-mail is set to the given destination address.

```

Note: I'm not sure how github adds new lines here so double check that this suggestion doesn't add an extra newline. There should only be a single newline before and after this sentence.

2024-02-06 19:01 UTC, rmathew1011 commented on books-call-number/nodes/email.json
> +  "name": "Email checked-out items list",
Correction in place

2024-02-06 19:03 UTC, rmathew1011 commented on books-call-number/triggers/startTrigger.json
> +  "name": "FOLIO Create Book Report Workflow Trigger",
Start trigger naming structure modified as per suggestion.

2024-02-06 19:39 UTC, wwelling commented on books-call-number/nodes/email.json
> +  "mailFrom": "{{bcn-mail-from}}",
Variable substitution (templating) from fw-cli configuration should be either `{{var}}` or `{{{var}}}`. This is handlebars syntax as used in the [template.service.ts](https://github.com/TAMULib/fw-cli/blob/main/src/service/template.service.ts) of fw-cli. The difference is whether or not the variable substitution should perform HTML escaping as defined by [Handlebars docs](https://handlebarsjs.com/guide/#html-escaping).

The syntax `${}` is from [FreeMarker templates](https://freemarker.apache.org/docs/dgui_quickstart_basics.html) as used in the [Java Delegates in mod-camunda](https://github.com/search?q=repo%3Afolio-org%2Fmod-camunda%20FreeMarkerTemplateUtils&type=code).

2024-02-06 19:42 UTC, wwelling commented on README.md
> +fw config set bcn-mail-from ***
Please see my comment above regarding the various methods of templating within fw-registry JSON files. If escaping the variable value is required use `{{{var}}}` otherwise `{{var}}` will still work as expected.

2024-02-06 20:29 UTC, kaladay commented on books-call-number/nodes/email.json
> +  "mailFrom": "{{bcn-mail-from}}",
In light of this information, please change this to use three braces for both of those variables.

2024-02-06 20:40 UTC, rmathew1011 commented on README.md
> +
Workflow description updated.

2024-02-06 20:57 UTC, rmathew1011 commented on README.md
> +User can inititate form submission from catalog_reports Book-Call-Number Report.
Added Curl for this workflow

2024-02-06 20:57 UTC, rmathew1011 commented on README.md
> +
Correct format introduced for describing the input variables

2024-02-06 21:03 UTC, rmathew1011 commented on README.md
> +fw config set bcn-mail-from ***
Wiki documentation was updated along with the Config file templates.
This works - we were able to receive email for this workflow.

2024-02-06 21:03 UTC, rmathew1011 commented on books-call-number/nodes/js/buildQuery.js
> +  ')';
Resolved

2024-02-06 21:04 UTC, rmathew1011 commented on books-call-number/nodes/query.json
> +  "name": "Query list of books by call number.",
Resolved

2024-02-06 21:04 UTC, rmathew1011 commented on books-call-number/nodes/zipReport.json
> +  "name": "Compress book report",
Resolved

2024-02-08 16:39 UTC, kaladay requested changes

2024-02-08 16:39 UTC, kaladay commented on README.md
> +| ldp-url        | URL            | LDP URL. |
This is missing the `bcn-mail-to` and `bcn-mail-from` rows.

2024-02-08 16:39 UTC, kaladay commented on README.md
> +fw config set bcn-mail-from ***
Three braces are need to NOT escape HTML.
Three braces uses raw values.

2024-02-08 16:39 UTC, kaladay commented on books-call-number/nodes/email.json
> +  "mailFrom": "{{bcn-mail-from}}",
Please change these to three braces because two braces escapes HTML and we don't want escaped HTML in an e-mail address.

2024-02-08 17:02 UTC, rmathew1011 commented on README.md
> +| ldp-url        | URL            | LDP URL. |
Added the 2 missing variables

2024-02-09 16:27 UTC, Dbreck-TAMU commented on README.md
> +| ldp-url        | URL            | LDP URL. |
Updated readme description, please see commit 722a6dd3ac7b23ca2014647665b2b09268851968

2024-02-09 16:27 UTC, Dbreck-TAMU commented on README.md
> +fw config set bcn-mail-from ***
Resolved issue, please see 316b5f859f9940b47446f8bba76e0c13c63f56ab

2024-02-09 16:28 UTC, Dbreck-TAMU commented on books-call-number/nodes/email.json
> +  "mailFrom": "{{bcn-mail-from}}",
Resolved issue, please see 316b5f859f9940b47446f8bba76e0c13c63f56ab

2024-02-09 16:28 UTC, Dbreck-TAMU commented on books-call-number/nodes/email.json
> +
Issue resolved

2024-02-09 19:50 UTC, kaladay commented on README.md
> +| bcn-mail-to    | e-mail address | An e-mail address used for testing the workflow. |
This doesn't sound correct.
Shouldn't this be an e-mail address destination rather than "for testing the workflow".

2024-02-09 19:54 UTC, kaladay commented on README.md
> +User can inititate form submission from catalog_reports Book-Call-Number Report.
This curl should use the `application/json` rather then the multipart and pass json data rather than form data.

2024-02-09 20:05 UTC, kaladay requested changes

2024-02-09 20:05 UTC, kaladay commented on README.md
> +  --form 'password="***"'
The `multipart/form-data` should only be used when uploading a file.
The proper curl example would be to use `application/json` with `--data-raw` rather than `--form`.

Below is an example suggestion, but you should double check and make sure that it works.
```suggestion
curl --location --request POST 'http://localhost:9001/mod-workflow/events/workflow/books-call-number/start' \
  --header 'Content-Type: application/json' \
  --header 'X-Okapi-Tenant: diku' \
  --data-raw '{ "logLevel": "INFO", "emailFrom": "folio@k1000.library.tamu.edu", "emailTo": "recipient@tamu.edu", "startRange": "a0", "endRange": "b9", "username": "***", "password": "***" }'
```

2024-02-09 21:46 UTC, Dbreck-TAMU commented on README.md
> +| bcn-mail-to    | e-mail address | An e-mail address used for testing the workflow. |
Resolved in commit 17793da0c731b277e9f1a79317eb50259cdfc79e

2024-02-09 21:46 UTC, Dbreck-TAMU commented on README.md
> +  --form 'password="***"'
Resolved, please see commit 17793da0c731b277e9f1a79317eb50259cdfc79e

2024-02-10 15:41 UTC, merged