Sprint15 staging community 2
TAMULib/fw-registry pull request #331
Opened 2024-02-12 14:57 UTC by kaladay

Contains sprint 15 changes merged with the folio community sprint 2 changes.

2024-02-13 16:46 UTC, wwelling requested changes

2024-02-13 16:46 UTC, wwelling commented on README.md
> +fw config set bcnMailTo ***
`bcnMailTo` is a variable from the request to start the workflow. The fw-cli configurations are for variables that do not change for each new instance of a workflow. I see `bcnMailFrom` is documented below as part of the request as well but not used the same in the workflow node JSON file.

https://github.com/TAMULib/fw-registry/pull/331/files#diff-0341fa1923c71df52d30064d65c396d9cd4b5348236c03e310eb6dd81756d67aR22

Can we make these consistent and accurately documented?

2024-02-13 16:55 UTC, Dbreck-TAMU commented on README.md
> +fw config set bcnMailTo ***
Documentation updated!

2024-02-14 17:59 UTC, wwelling commented on books-call-number/nodes/buildQuery.json
> +  "description": "Build Query using input parameters - startRange and endRange.",
Can we update the description to not include required variables? It would be good to know what the required input variables for the task are but not sure we want to convolute the description. We do not want to maintain descriptions for when variables change for a given task. Additionally, the JavaScript query also requires `logLevel`. I would like to discuss where we should document and manage the process and local variables used within a workflow. Should they be a property on a persistent entity to be able to perform input checks once per workflow and not at every workflow. Such as the setup task iterate over the tasks and determine if any input/output variable is used or not and what scope.

2024-02-14 18:04 UTC, wwelling commented on books-call-number/nodes/buildQuery.json
> +  "description": "Build Query using input parameters - startRange and endRange.",
The setup task can provide fail fast incident which can provides more details in the exception for preventing arbitrary task failure. It would be location for workflow server-side validation. Are all the require variables defined and correct type?

2024-03-06 18:37 UTC, kaladay commented on books-call-number/nodes/buildQuery.json
> +  "description": "Build Query using input parameters - startRange and endRange.",
None of these are changes from the community sprint and these requests are out of scope.
Their respective PRs should have had these reviews.

That PR is here: https://github.com/TAMULib/fw-registry/pull/329

2024-03-21 15:48 UTC, closed without merging