Does this work?
TAMULib/fw-registry pull request #343
Opened 2024-03-21 16:44 UTC by wwelling

2024-03-21 18:48 UTC, wwelling commented on README.md
> +--form 'path="/mnt/workflows/diku/create-tags"' \
https://github.com/TAMULib/fw-registry/pull/342#discussion_r1534165064

2024-03-21 19:17 UTC, kaladay requested changes

2024-03-21 19:17 UTC, kaladay commented on remove-books-from-nbs/nodes/email.json
> +  "mailFrom": "${{nbs-mail-from}}",
Please fix this and replace `${{nbs-mail-from}}` with `${nbsMailFrom}`.
The `-` cannot be used in the names and we should only have a single braces not double braces.

2024-03-21 19:17 UTC, kaladay commented on README.md
> +## Variable substitution
I didn't request for this to be added here.

Do we really want this documentation here?
I'm fine if it is, I just wanted to be clear that this was not the request I made.

My request was to either update the wiki if `${{}}` is valid or fix the invalid syntax.

Also, it is not freemarker syntax that we area dealing with.
It is camunda syntax.
see: https://docs.camunda.org/manual/7.18/user-guide/process-engine/expression-language/

2024-03-21 20:26 UTC, wwelling commented on README.md
> +## Variable substitution
Could you please provide a link to the Wiki in your request to update it?

2024-03-21 20:31 UTC, wwelling commented on README.md
> +## Variable substitution
Oh and we didn't even correct it yet. Please see latest commit.

2024-03-21 20:33 UTC, wwelling commented on remove-books-from-nbs/nodes/email.json
> +  "mailFrom": "${{nbs-mail-from}}",
It should be `{{nbs-mail-from}}` as it is not a catalog reports form input variable. Do we want catalog reports defining these "global" to all workflows email from? 

Or are you requesting it be hardcoded in the catalog reports trigger form submit? Which issues POST request to mod-workflow.

2024-03-21 20:37 UTC, wwelling commented on README.md
> +## Variable substitution
Also, not all using `${}` syntax are processed by camunda. But I did miss those in the added description. 

However, the email task to email delegate uses freemarker in the delegate. Perhaps some improvements can be made.

https://github.com/TAMULib/mod-camunda/blob/main/src/main/java/org/folio/rest/delegate/EmailDelegate.java#L38
https://github.com/TAMULib/mod-camunda/blob/main/src/main/java/org/folio/rest/delegate/EmailDelegate.java#L70

2024-03-21 20:37 UTC, wwelling commented on README.md
> +## Variable substitution
Here is an example of Camunda expression evaluation.

https://github.com/TAMULib/fw-registry/pull/343/files#diff-7d2047632ca971bdfd3275170d756fe41a0244395fd1bdd7572aa05d31a4fdb0R14

2024-03-21 20:43 UTC, wwelling commented on README.md
> +## Variable substitution
Please see latest commit updating the readme.

2024-03-21 20:45 UTC, wwelling commented
> My request was to either update the wiki if ${{}} is valid or fix the invalid syntax.

@kaladay the syntax `${{}}` is invalid I think.

2024-03-22 18:33 UTC, wwelling commented on README.md
> +## Variable substitution
> I didn't request for this to be added here.
> 
> Do we really want this documentation here? I'm fine if it is, I just wanted to be clear that this was not the request I made.
> 
> My request was to either update the wiki if `${{}}` is valid or fix the invalid syntax.
> 
> Also, it is not freemarker syntax that we area dealing with. It is camunda syntax. see: https://docs.camunda.org/manual/7.18/user-guide/process-engine/expression-language/

The change request comment is easily misinterpreted. Anyhow, I would add this documentation in the README.

<img width="609" alt="image" src="https://github.com/TAMULib/fw-registry/assets/144841721/66d27e65-c119-41ea-acf2-50b07f798621">

2024-03-26 15:33 UTC, Dbreck-TAMU approved these changes

2024-03-26 15:35 UTC, kaladay requested changes
This set is to go into sprint17-staging.
I think this is the wrong staging branch.

2024-03-26 18:53 UTC, merged

2024-03-26 19:59 UTC, kaladay commented on remove-books-from-nbs/nodes/email.json
> +  "mailMarkup": "${email.markup}",
This is inconsistent.
`emailTo` and `email.text`.