347 evans pres repr report
TAMULib/fw-registry pull request #349
Opened 2024-04-22 19:20 UTC by rmathew1011

Resolves #347

2024-04-23 15:45 UTC, kaladay requested changes

2024-04-23 15:45 UTC, kaladay commented on README.md
> +This workflows sends out a monthly email a list of all items  with a temporary location of **Eva Pres Repr** for a specific configured email address **evansPresReprFrom**.
Remove extra space and improve grammar.
```suggestion
This workflows sends out a monthly email of a list of all items with a temporary location of **Eva Pres Repr** for a specific configured email address `evansPresReprFrom`.
```

2024-04-23 15:45 UTC, kaladay commented on evans-pres-repr/nodes/query.json
> +  "description": "Query items with temp loc of Evans Pres Repr",
Please make this a complete sentence without as many acronyms.
This does not need to be short like the title (name).
I suggest using single quotes to handle the specially named `Evans Pres Repr`.

2024-04-23 15:45 UTC, kaladay commented on evans-pres-repr/workflow.json
> +  "description": "Generate monthly Evans Pres Repr report.",
I suggest using single quotes to handle the specially named `Evans Pres Repr`.

2024-04-23 15:45 UTC, kaladay commented on evans-pres-repr/nodes/email.json
> +  "description": "",
Add description.

2024-04-23 15:45 UTC, kaladay commented on evans-pres-repr/nodes/delete.json
> +  "description": "",
Add description.

2024-04-23 15:45 UTC, kaladay commented on evans-pres-repr/nodes/connect.json
> +  "description": "",
Add description.

2024-04-23 15:45 UTC, kaladay commented on evans-pres-repr/nodes/email.json
> +  "mailText": "${(count > 0)?then('Monthly Evans Pres Repr CSV file attached', 'No results to report')}",
```suggestion
  "mailText": "${(count > 0) ? then('Monthly Evans Pres Repr CSV file attached', 'No results to report')}",
```

2024-04-23 15:45 UTC, kaladay commented on evans-pres-repr/nodes/email.json
> +  "includeAttachment": "${(count > 0)?then('true', 'false')}",
```suggestion
  "includeAttachment": "${(count > 0) ? then('true', 'false')}",
```

2024-04-23 15:45 UTC, kaladay commented on evans-pres-repr/nodes/end.json
> +  "description": "End Task",
Make this a sentence.

2024-04-23 15:45 UTC, kaladay commented on evans-pres-repr/nodes/start.json
> +  "description": "",
Add description.

2024-04-23 15:45 UTC, kaladay commented on README.md
> +fw run evans-pres-repr
Please follow the practice of adding the table, such as is done here:
- https://github.com/TAMULib/fw-registry/blob/59e0027ceb7aa65cc700e8e81e1df7050012c8f9/README.md#books-call-number

2024-04-23 15:45 UTC, kaladay commented on evans-pres-repr/nodes/disconnect.json
> +  "description": "",
Add description.

2024-04-23 17:20 UTC, rmathew1011 commented on README.md
> +This workflows sends out a monthly email a list of all items  with a temporary location of **Eva Pres Repr** for a specific configured email address **evansPresReprFrom**.
Removed extra space and improved grammar.

2024-05-01 02:25 UTC, rmathew1011 commented on evans-pres-repr/nodes/start.json
> +  "description": "",
Description Added.

2024-05-01 02:26 UTC, rmathew1011 commented on evans-pres-repr/nodes/end.json
> +  "description": "End Task",
Made a sentence.

2024-05-01 02:27 UTC, rmathew1011 commented on evans-pres-repr/nodes/email.json
> +  "includeAttachment": "${(count > 0)?then('true', 'false')}",
Added space before and after '?'

2024-05-01 02:27 UTC, rmathew1011 commented on evans-pres-repr/nodes/email.json
> +  "mailText": "${(count > 0)?then('Monthly Evans Pres Repr CSV file attached', 'No results to report')}",
Added space before and after '?'

2024-05-01 02:28 UTC, rmathew1011 commented on evans-pres-repr/nodes/connect.json
> +  "description": "",
Description added.

2024-05-01 02:55 UTC, rmathew1011 commented on evans-pres-repr/nodes/delete.json
> +  "description": "",
Description added.

2024-05-02 15:44 UTC, qtamu approved these changes

2024-05-02 16:36 UTC, rmathew1011 commented on README.md
> +| path                    | directory path | The directory on the system where the files, like the CSV file, are stored within on the server and contain the `tenantPath` (include trailing slash after
Removed path variable as we have the path value hard coded in the database query delegate task.

2024-05-02 18:04 UTC, kaladay approved these changes

2024-05-02 19:02 UTC, merged