Example emailTask Workflow
TAMULib/fw-registry pull request #361
Opened 2024-05-30 18:43 UTC by rhundal7

- Sends an email

2024-05-30 19:03 UTC, kaladay requested changes

2024-05-30 19:03 UTC, kaladay commented on examples/example-emailtask/nodes/email.json
> +      }
None of these are being used and should be deleted.
```suggestion
```

Alternatively, we may want to change `mailTo` into a configurable variable and keep the `exampleEmailTo` process variable:

```suggestion
      {
        "key": "exampleEmailTo",
        "type": "PROCESS"
      }
```

2024-05-30 19:03 UTC, kaladay commented on examples/example-emailtask/nodes/email.json
> +    "mailTo": "{{exampleEmailTo}}",
```suggestion
    "mailTo": "${exampleEmailTo}",
```
If we go with a process variable, then this change is needed.

2024-06-01 20:26 UTC, rhundal7 commented on examples/example-emailtask/nodes/email.json
> +    "mailTo": "{{exampleEmailTo}}",
done

2024-06-01 20:28 UTC, rhundal7 commented on examples/example-emailtask/nodes/email.json
> +    "mailMarkup": "<html><head><title>Example Email</title></head><body> <p> Text for Email </p> <body></html>",
done

2024-06-01 20:50 UTC, rhundal7 commented on examples/example-emailtask/nodes/email.json
> +    "mailFrom": "{{exampleEmailFrom}}",
Initial commit pushed - wip

2024-06-03 14:16 UTC, kaladay requested changes

2024-06-03 14:16 UTC, kaladay commented on examples/example-emailtask/nodes/email.json
> +    }
```suggestion
    }
```
I don't think the `timestamp` and `tenantId` are needed.

2024-06-03 14:16 UTC, kaladay commented on examples/README.md
> +| password       | string         | Okapi login password. |
```suggestion
| username       | string         | Okapi login username. |
| password       | string         | Okapi login password. |
```

I don't think these are needed for sending an e-mail.

2024-06-03 14:16 UTC, kaladay commented on examples/README.md
> +fw config set exampleEmailTo ***
```suggestion
```
This is no longer a fw config parameter and is a request parameter.
Please remove.

2024-06-03 14:16 UTC, kaladay commented on examples/README.md
> +| emailTo        | e-mail address | An e-mail address used as the "TO" in the sent e-mails. |
```suggestion
| Variable Name    | Allowed Values | Short Description |
| ---------------- | -------------- | ----------------- |
| exampleEmailFrom | e-mail address | The source e-mail address to send from. |
| exampleEmailTo   | e-mail address | The destination e-mail address to send to. |
```

The table should describe the properties the task is needing.

2024-06-03 15:50 UTC, kaladay commented on examples/README.md
> +| logLevel       | [INFO,DEBUG]   | Desired log level |
```suggestion
| Variable Name    | Allowed Values | Short Description |
| ---------------- | -------------- | ----------------- |
| exampleEmailFrom | e-mail address | The source e-mail address to send from. |
| exampleEmailTo   | e-mail address | The destination e-mail address to send to. |
| logLevel         | [INFO,DEBUG]   | Desired log level |
```

2024-06-03 17:30 UTC, kaladay requested changes

2024-06-03 17:30 UTC, kaladay commented on examples/README.md
> +  --data-raw '{ "logLevel": "INFO", "exampleEmailFrom": "*", "username":"diku","password":"*", "exampleEmailTo": "you@example.com" }'
Don't put the TAMU specific URL here.
It should be something like `http://localhost:9001/` ...

Also, the example data needs to be reasonably correct.
The configuration is wrong.
There should be no `username`, `password`, or `exampleEmailFrom`.

Try something like this:

```suggestion
curl --location --request POST 'http://localhost:9001/mod-workflow/events/workflow/example-emailtask/start' \
  --header 'Content-Type: application/json' \
  --header 'X-Okapi-Tenant: diku' \
  --data-raw '{ "logLevel": "INFO", "exampleEmailTo": "you@example.com" }'
```

2024-06-06 17:59 UTC, kaladay approved these changes

2024-06-07 21:04 UTC, merged