fix query to filter on effective location
TAMULib/fw-registry pull request #381
Opened 2024-06-24 18:47 UTC by rhundal7

- PR for issue https://github.com/TAMULib/fw-registry/issues/378

2024-07-01 13:43 UTC, rmathew1011 requested changes

2024-07-01 13:43 UTC, rmathew1011 commented on books-call-number/nodes/js/buildQuery.js
> -if (logLevel === 'DEBUG') {
Could you have this if condition back.

2024-07-01 13:43 UTC, rmathew1011 commented on books-call-number/nodes/js/buildQuery.js
> +where = '\n\t\tUPPER(ie.effective_call_number) >= UPPER(\'' + startRange + '\')';
Check for the indentation here

2024-07-01 13:43 UTC, rmathew1011 commented on books-call-number/nodes/js/buildQuery.js
> +where += '\n\t\tAND UPPER(ie.effective_call_number) <= RPAD(UPPER(\'' + endRange + '\'), max_len, \'ÿ\')';
could you add extra space  - code is within if block.

2024-07-01 13:43 UTC, rmathew1011 commented on books-call-number/nodes/js/buildQuery.js
> + print(locationNameArray);
could you add extra space - code is within if block.

2024-07-01 13:43 UTC, rmathew1011 commented on books-call-number/nodes/js/buildQuery.js
> +'\n\n' + cte +
could you bring in the  if condition.

2024-07-01 13:43 UTC, rmathew1011 commented on books-call-number/nodes/js/buildQuery.js
> -  sql: booksCallNumberQuery,
could you add extra space - code is within a block.

2024-07-01 17:45 UTC, Dbreck-TAMU commented on books-call-number/nodes/js/buildQuery.js
> +execution.setVariableLocal('booksCallNumberQuery', S(JSON.stringify(queryWrapper)));
Please add EoF Line. 
```suggestion
execution.setVariableLocal('booksCallNumberQuery', S(JSON.stringify(queryWrapper)));

```

2024-07-01 17:56 UTC, Dbreck-TAMU commented on books-call-number/nodes/js/buildQuery.js
> +}
Code suggestion for clarity: 

const locationNames = execution.getVariable('locationName') || [];
const MAX_ALLOWED_CHARACTERS = 3000;

if (MAX_ALLOWED_CHARACTERS < locationNames.length) {
  throw new Error("Selection exceeds the maximum allowed character count.");
}

var locationNameArray = JSON.parse(locationName);

2024-07-01 18:03 UTC, rhundal7 commented on books-call-number/nodes/js/buildQuery.js
> +}
I will most likely be removing this block 
```
if (totalCharacterCount > maxAllowedCharacters) {
   throw new Error("Selection exceeds the maximum allowed character count.");
}
```

2024-07-01 20:06 UTC, wwelling commented on books-call-number/nodes/js/buildQuery.js
> +const locationNames = execution.getVariable('locationName') || [];
```suggestion

```

2024-07-01 20:06 UTC, wwelling commented on books-call-number/nodes/js/buildQuery.js
> +let totalCharacterCount = 0;
```suggestion
let totalCharacterCount = locationName.length;
```

2024-07-01 20:09 UTC, wwelling commented on books-call-number/nodes/js/buildQuery.js
> +for (var i = 0; i < locationNames.length; i++) {
As locationNames is the serialized string on the context and it is what can exceed the history table max column for variable value, iterating over the string counting characters is not necessary.

2024-07-01 20:10 UTC, wwelling commented on books-call-number/nodes/js/buildQuery.js
> +  print('locationName = ' + locationName + '\n');
```suggestion
  print('\nlocationName = ' + locationName + '\n');
```

2024-07-01 20:12 UTC, wwelling requested changes
No need to get variables using the execution context, they are already available in the JavaScript scope.

2024-07-01 20:16 UTC, wwelling commented on books-call-number/nodes/js/buildQuery.js
> +if (locationNameArray.length > 0 && locationNameArray.length < totalCharacterCount) {
locationNameArray.length < totalCharacterCount is always going to be less than the total number of characters summing the location names.
```suggestion
if (locationNameArray.length > 0 && totalCharacterCount  <= maxAllowedCharacters ) {
```

2024-07-01 21:04 UTC, wwelling commented on books-call-number/nodes/js/buildQuery.js
> +const maxAllowedCharacters = 3000;
```suggestion
```

2024-07-01 21:04 UTC, wwelling commented on books-call-number/nodes/js/buildQuery.js
> +let totalCharacterCount = 0;
```suggestion
```

2024-07-02 13:26 UTC, wwelling commented on books-call-number/nodes/js/buildQuery.js
> +const locationNames = execution.getVariable('locationName');
Can this be removed and just use the variable `locationName` that is already on the scope?

2024-07-02 15:40 UTC, kaladay requested changes

2024-07-02 15:40 UTC, kaladay commented on books-call-number/nodes/js/buildQuery.js
>  var where = 'TRUE';
```suggestion

var where = 'TRUE';
```
Add back missing new line.

2024-07-02 15:40 UTC, kaladay commented on books-call-number/nodes/js/buildQuery.js
>  if (startRange) {
```suggestion
if (!!startRange) {
```

Being that this is JavaScript, we do not want to rely of the boolean check on the variable.
Instead, use a double exclamation, like `!!`.

Please do the same for the `if (endRange) {` below.

2024-07-02 15:40 UTC, kaladay commented on books-call-number/nodes/js/buildQuery.js
>  ')';
```suggestion
  '\n\tSELECT MAX(LENGTH(ie.effective_call_number)) AS max_len' +
  '\n\tFROM folio_reporting.item_ext ie' +
  ')';
```

2024-07-02 15:40 UTC, kaladay commented on books-call-number/nodes/js/buildQuery.js
> +  where += "\n\tAND ie.effective_location_name IN ('"+locationNameArray.join("', '")+"')";
```suggestion
  where += "\n\tAND ie.effective_location_name IN ('" + locationNameArray.join("', '") + "')";
```

2024-07-02 18:08 UTC, kaladay approved these changes

2024-07-02 21:45 UTC, wwelling approved these changes

2024-07-05 15:26 UTC, rmathew1011 approved these changes

2024-07-08 12:35 UTC, merged