Description added for patron workflow nodes
TAMULib/fw-registry pull request #392
Opened 2024-09-05 19:09 UTC by rmathew1011

2024-09-05 19:38 UTC, kaladay requested changes

2024-09-05 19:38 UTC, kaladay commented on patron/nodes/others.json
> +  "description": "Executes queries on other patrons in divIt database.",
```suggestion
  "description": "Executes queries on other patrons in DivIt database.",
```

2024-09-05 19:38 UTC, kaladay commented on patron/nodes/students.json
> +  "description": "Executes query on 'student' patrons from 'divit' database.",
```suggestion
  "description": "Executes query on student patrons from DivIT database.",
```

2024-09-05 19:38 UTC, kaladay commented on patron/nodes/studentsConnectTo.json
> +  "description": "Connects to parallel gateway to complete 'student' task.",
```suggestion
  "description": "Connects to parallel gateway to complete student task.",
```

2024-09-05 19:38 UTC, kaladay commented on patron/nodes/studentsMoveToNode.json
> +  "description": "Routes workflow to 'Students' node, connects to gateway, executes query and connection task.",
```suggestion
  "description": "Routes workflow to students node, connects to gateway, executes query and connection task.",
```

2024-09-05 19:38 UTC, kaladay commented on patron/nodes/transform.json
> +  "description": "Exceutes Javascript to process patron objects.",
```suggestion
  "description": "Transforms the database results into processable objects.",
```

2024-09-05 20:55 UTC, rmathew1011 commented on patron/nodes/others.json
> +  "description": "Executes queries on other patrons in divIt database.",
Changes made.

2024-09-05 20:55 UTC, rmathew1011 commented on patron/nodes/students.json
> +  "description": "Executes query on 'student' patrons from 'divit' database.",
Changes made.

2024-09-05 20:56 UTC, rmathew1011 commented on patron/nodes/studentsConnectTo.json
> +  "description": "Connects to parallel gateway to complete 'student' task.",
Changes made.

2024-09-05 20:56 UTC, rmathew1011 commented on patron/nodes/studentsMoveToNode.json
> +  "description": "Routes workflow to 'Students' node, connects to gateway, executes query and connection task.",
Changes made.

2024-09-05 20:57 UTC, rmathew1011 commented on patron/nodes/transform.json
> +  "description": "Exceutes Javascript to process patron objects.",
Changes made.

2024-09-06 15:22 UTC, kaladay approved these changes

2024-09-06 15:26 UTC, merged